app:
  image: mohamedsherif20/instabug_intern:latest
  replicas: 1
  port : 9090
  username: root
  password: mypassword
  mysql_port: 3306


mysql:
  image: mysql:latest
  rootPassword: mypassword


