version: '3.3'


services:

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  app:
    image: mohamedsherif20/instabug_intern:latest
    ports:
       - "9090:9090"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=1234
      - MYSQL_PORT=3306
    depends_on:
      - mysql
    restart: "always"
  
