apiVersion: apps/v1
kind: Deployment
metadata:
  name: instabug
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "{{.Values.app.mysql_port}}"
            - name: MYSQL_USER
              value: {{ .Values.app.username }}
            - name: MYSQL_PASS
              value: "{{.Values.mysql.rootPassword}}"
          resources:
            requests:
              cpu: 100m
              memory: 500Mi